name = "MathJuMPAccessories"
uuid = "f469ccb0-c07c-42c4-84e9-4124f3b4a9c2"
authors = ["Jo√£o Rodrigo da Silva Muniz"]
version = "1.0.0-DEV"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.10.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
